### ISSUE TITLE
Вопрос: Из описания непонятно, по какому "публичному API" будет создана документация. Пояснишь?

### ISSUE THREAD

**Issue by artbear** [khorevaa/oscript-documentator#1]
>Приложение и библиотека для автоматической геренации документации по публичному API для Oscript

Из описания непонятно, по какому "публичному API" будет создана документация. Пояснишь?

Экспортные методы onescript-скриптов или что еще?

**Comment by khorevaa** [comment]
Да по всем экспортным методам .os и .bsl файлов.
А так же ряд не экспортных методов .os типа `ПриСозданииОбъекта`

**Comment by artbear** [comment]
Ага, так понятнее.
Добавишь в доку?

**Comment by khorevaa** [comment]
Да когда сделаю либу ))

**Comment by artbear** [comment]
Сейча просто добавь в ридми написанные тобой выше ДВЕ строчки.
Этого достаточно на текущий момент :)

**Comment by khorevaa** [comment]
Хорошо :)

**Comment by khorevaa** [comment]
добавил!
